### ISSUE TITLE
What is different about this tool regarding nmap -O/nmap -A?

### ISSUE THREAD

**Issue by q2dg** [xnih/satori#1]
Thanks!

**Comment by xnih** [comment]
nmap is an active scanner, it has to send packets out to determine the OS.
For it to be able to determine the OS, the system has to respond to those
packets.  If the local FW is enabled on the device nmap is scanning, it
will fail to be able to detect the OS running on the device.   Satori on
the other hand is a passive program, it utilizes the packets it sees the
system sending out already to determine the OS.  Both programs have their
specific uses and short comings.

Satori ultimately needs to be able to see traffic from a system you're
trying to fingerprint or determine the OS on.   In some cases, such as SMB
or DHCP, it just needs to be on the same segment and then it will see the
broadcast packets that the system sends out.  In other cases, such as TCP
or HTTP it needs to be able to see the traffic that isn't designated to the
system running satori, so you'll need to have a span or tap setup and feed
that network traffic to satori.

**Comment by xnih** [comment]
As this isn't actually an issue with Satori, I've moved this information over to the wiki:  https://github.com/xnih/satori/wiki

I'll leave this here for now, but will eventually close/delete it, but wanted to leave it here for the time being in case there were other specific questions related to this topic.

**Comment by q2dg** [comment]
Oooh, thanks a lot for your splendid explanation! I think this information is really great for being available in wiki, yes!

If you don't mind, I'll close this issue  because I think it's pretty clear. Feel free to reopen it if you consider

Thanks!
