### ISSUE TITLE
help

### ISSUE THREAD

**Issue by whitepoet** [xnih/satori#2]
can you give me the paper of thie project,i can not  download it。
thanks!
zjxu_r@outlook.com,this is my email

**Comment by xnih** [comment]
In case anyone else is looking for them, currently you can find the different papers archived off on other systems.  I'll try to find the originals from backups and put them out here eventually.

There was never specifically a paper on Satori, but there were a few other papers that were released over the years that were based on the findings I had from Satori and from normal packet captures.

If you do a google search for:
chatter on the wire a look at dhcp traffic

The original OS fingerprinting paper is still up on packetstormsecurity:
https://dl.packetstormsecurity.net/papers/general/OSFingerPrint.pdf  

The DHPC ones can be found in the web archive:
https://web.archive.org/web/20161222050148fw_/http://chatteronthewire.org/papers.htm 

DHCP - 2007:
https://web.archive.org/web/20180519190614fw_/http://chatteronthewire.org/download/chatter-dhcp.pdf

DHCPv6 - 2010
https://web.archive.org/web/20160308075724fw_/http://chatteronthewire.org/download/chatter-dhcpv6.pdf
