### ISSUE TITLE
Licensing question regarding files in this repository

### ISSUE THREAD

**Issue by daluu** [xnih/satori#20]
So the code or files in general in this repo follow the license set for the repository: GPL v2.

I noticed the fingerprint database files have a note about terms of use. So just wanted to clarify those fingerprint files follow that terms of use rather than the repo's GPL v2 licensing? Or it is a combination of both to be followed when using?

**Comment by xnih** [comment]
I'll look at updating the information in the fingerprint files in the coming weeks, this is left over from when the product was a windows program and the fingerprints, specifically DHCP were brand new after our Black Hat 2007 presentation and was trying to make sure companies weren't just stealing them and putting them in their products without some info about where they got them from.

Short answer, I'll be updating it to GPL v2 when I get around to it, so if you want to use them now, treat it that way, no need to notify me anymore if you don't want, but I'm always happy to see other products doing passive fingerprinting and happy to test and provide feedback if desired.

Hope that helps/clarifies.

**Comment by xnih** [comment]
Updated all the fingerprint files to remove that "requirement", so should all fall under same licensing now.  Thanks for the heads up/reminder on that.
