### ISSUE TITLE
Fingerprint contributions process clarification

### ISSUE THREAD

**Issue by daluu** [xnih/satori#21]
Regarding the contribution of fingerprints as mentioned in the fingerprint files, it doesn't mention details, and is less specific a process compared to contributions to nmap fingerprints. So I thought it useful to ask for clarifications for the general public:

* provide fingerprint info in a github issue or pull request?
* provide raw fingerprint value/info for whichever type of fingerprint, or you are expecting it to be in satori's XML format, basically modifying your existing fingerprint file?
* applicable to coming up with / generating (new) fingerprints from satori (software), or from any source where fingerprint was obtained but to which the type of fingerprint matches one that satori supports?

**Comment by xnih** [comment]
I haven't had many additions from 3rd parties in years.  Back when it was a windows program people emailed dhcpfingerprints@gmail.com, I still own that account and you're welcome to email them there (for any fingerprint format, most were dhcp back in the day).

I have had a one or two pull requests to add new ones in the past.  As I'm not a big github user it normally takes me some poking around to remember how to approve it and get it merged.  Happy to take them this way, but direct email works fine.  You'll just want to make sure you understand the formatting.  Adding a new fingerprint to an existing fingerprint is easy, a completely new OS/Application may be a little more problematic if you are doing it by hand.  To make it easier there is a windows program that will read in the files and makes updating the fingerprint file a lot easier.  

Fingerprint Editor:
https://github.com/cycocrew/devonic  

This is a tool that one of the original people that helped provide many of the early fingerprints and has updated it periodically as I add new fingerprint files to the product that weren't in the original windows version.

If you have any new fingerprints or updates that are need you can also just provide the raw output from satori to the email address above and I'll get it added and updated within a few days.
